interface PersonalValueDefinition {
  key: string;
}

export const personalValuesList: PersonalValueDefinition[] = [
  { key: "accepting" },
  { key: "affectionate" },
  { key: "aspiring" },
  { key: "assertive" },
  { key: "authentic" },
  { key: "caring" },
  { key: "challenging" },
  { key: "compassionate" },
  { key: "conforming" },
  { key: "cooperating" },
  { key: "courageous" },
  { key: "creative" },
  { key: "curious" },
  { key: "emotionally-aware" },
  { key: "encouraging" },
  { key: "equality" },
  { key: "fairness" },
  { key: "fitness" },
  { key: "flexible" },
  { key: "forgiving" },
  { key: "friendliness" },
  { key: "generosity" },
  { key: "gratitude" },
  { key: "honesty" },
  { key: "humility" },
  { key: "humour" },
  { key: "independent" },
  { key: "industrious" },
  { key: "open-minded" },
  { key: "orderly" },
  { key: "patient" },
  { key: "respectful" },
  { key: "safe" },
  { key: "self-aware" },
  { key: "self-disciplined" },
  { key: "tenacious" },
  { key: "tolerant" },
  { key: "trusted" },
];
