export interface PersonalValueDefinition {
  key: string;
}

export const personalValuesList: PersonalValueDefinition[] = [
  { key: "accepting" },
  { key: "affectionate" },
  { key: "aspiring" },
  { key: "authentic" },
  { key: "balanced" },
  { key: "caring" },
  { key: "committed" },
  { key: "compassionate" },
  { key: "connected" },
  { key: "courageous" },
  { key: "creative" },
  { key: "dependable" },
  { key: "devoted" },
  { key: "empathic" },
  { key: "equitable" },
  { key: "expressive" },
  { key: "flexible" },
  { key: "focused" },
  { key: "forgiving" },
  { key: "free" },
  { key: "fun-loving" },
  { key: "generous" },
  { key: "grateful" },
  { key: "grounded" },
  { key: "honest" },
  { key: "humble" },
  { key: "independent" },
  { key: "inspired" },
  { key: "integrity" },
  { key: "kind" },
  { key: "open-minded" },
  { key: "optimistic" },
  { key: "patient" },
  { key: "peaceful" },
  { key: "playful" },
  { key: "purposeful" },
  { key: "resilient" },
  { key: "responsible" },
  { key: "self-aware" },
  { key: "spiritual" },
  { key: "supportive" },
  { key: "tolerant" },
  { key: "trustworthy" },
  { key: "wise" },
];
